name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          sparse-checkout: | 
              requirements.txt
              Dockerfile
              main.py
              LICENSE
              .gitignore
              driver/
          sparse-checkout-cone-mode: false
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hailstone-numbers:v1.0
      
    - name: Push to Releases
      run: | # update this for every major docker image release/update lmao
          docker push captainchicky/hailstone-numbers:v1.0

          release_name = "Hailstone Numbers Docker Image"
          release_body = "Docker image for Hailstone Numbers, version 1.0 with all dependencies installed."
          release_tag = "v1.0"
          run: | 
            curl -X POST https://api.github.com/repos/CaptainChicky/Hailstone-Numbers/releases \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d "{\"tag_name\":\"${release_tag}\",\"target_commitish\":\"main\",\"name\":\"${release_name}\",\"body\":\"${release_body}\",\"draft\":false,\"prerelease\":false}"
