name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          sparse-checkout: | 
              requirements.txt
              main.py
              LICENSE
              .gitignore
              driver/
          sparse-checkout-cone-mode: false
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hailstone-numbers:v1.0
      
    - name: Push to Releases
      run: | # update this for every major docker image release/update lmao
          docker push captainchicky/hailstone-numbers:v1.0
