name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          sparse-checkout: | 
              requirements.txt
              Dockerfile
              main.py
              LICENSE
              .gitignore
              driver/
          sparse-checkout-cone-mode: false
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hailstone-numbers:v1.0
      
    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0
        release_name: Release v1.0

    - name: Upload Docker image to GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          hailstone-numbers:v1.0
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v1.0