name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          sparse-checkout: | 
              requirements.txt
              Dockerfile
              main.py
              LICENSE
              .gitignore
              driver/
          sparse-checkout-cone-mode: false
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hailstone-numbers:v1.0
      
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./
        asset_name: hailstone-numbers
        asset_content_type: application/x-gzip