name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        sparse-checkout: | 
          requirements.txt
          Dockerfile
          main.py
          LICENSE
          .gitignore
          driver/
        sparse-checkout-cone-mode: false

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hailstone-numbers:v1.1

    - name: Save Docker image as tar file
      run: docker save hailstone-numbers:v1.1 > hailstone-numbers.tar

    - name: Create GitHub release #  The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: # remember to update this on every release. also, manually add body content to the release after publish
        tag_name: v1.1
        release_name: Docker Image v1.1

    - name: Upload Docker image to GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          hailstone-numbers.tar
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v1.1
